### ISSUE TITLE
Add number of people following (tracking?) a case to the show view

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#215]
The article/show page should include:
- [x] the number of people following a case (should this term be changed to "tracking" in line with our hashtag #wearetrackingthis ?)
- [x] links to a page with all users following a case, which will allow people to connect about a specific case?
- [x] maybe a user can message all other followers of a specific case?

**Comment by campgurus** [comment]
This may also help with SEO, by creating more pages that are potentially responsive to Search engine queries. This is also an argument for having the timeline as a separate page for each case.

**Comment by campgurus** [comment]
Add tests to:
- [] add notification to followers when a case is deleted
- [] confirm that @article follows are displayed when they exist
- [] confirm that non-logged in users attempting to follow are redirected to the login page

**Comment by campgurus** [comment]
this work is contained in branch: 215_work_in_progress

**Comment by trystant** [comment]
Hey, is this task done?

**Comment by campgurus** [comment]
Partially.  on every case/show page, we show the number of people tracking the case, and links to a page with all followers listed. so i guess the first two checklist items above

**Comment by trystant** [comment]
The third checkbox, having a user be able to message all other users following a case is not necessary, I don't think. What happens if two people following the case don't like each other? I'd remove that last requirement and consider this done for now.

**Comment by campgurus** [comment]
closing this as done.
